### ISSUE TITLE
Kafka sink and source

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/Alpakka#10]
This scala module could be used as a source: https://github.com/akka/reactive-kafka

This Kafka client is the best for .NET https://www.nuget.org/packages/Confluent.Kafka/

**Comment by Arkatufus** [comment]
Akka.Streams.Kafka have been moved out of Alpakka into its own Github repo.
Closing this issue. Please re-open them in https://github.com/akkadotnet/Akka.Streams.Kafka if you're still having this problem.
