### ISSUE TITLE
Kafka with Azure Event Hub

### ISSUE THREAD

**Issue by sleipnir** [akkadotnet/Alpakka#119]
I'm trying to find some example of using Akka.NET Streams to consume Kafka events from the Azure Event Hub. It seems to me that Kafka support does not support the authentication required to connect to Azure Hub, but I may be mistaken. If anyone has an example I would appreciate it very much.

I'm not actually a .Net developer by nature. In Java or Scala using Akka Streams I would configure my application like this:

```
akka {
  kafka.producer {
    #Akka kafka producer properties can be defined here
    client.id = "proxy-client"


    # Properties defined by org.apache.kafka.clients.producer.ProducerConfig
    # can be defined in this configuration section.
    kafka-clients {
      bootstrap.servers = "my-kafka.servicebus.windows.net:9093"
      sasl.mechanism = PLAIN
      security.protocol = SASL_SSL
      sasl.jaas.config = "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://my-kafka.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey={key}\";"
    }
  }
```
On the Gitter channel, Aaron told me that you support these options so it must be the case that you just find them. So an example would be welcome.

**Comment by Arkatufus** [comment]
`Akka.Streams.Kafka` is now a separate standalone project and are not part of the Alpakka repo, it is probably best if you move this issue to https://github.com/akkadotnet/Akka.Streams.Kafka

**Comment by sleipnir** [comment]
> `Akka.Streams.Kafka` is now a separate standalone project and are not part of the Alpakka repo, it is probably best if you move this issue to https://github.com/akkadotnet/Akka.Streams.Kafka

Thanks @Arkatufus
