### ISSUE TITLE
StartingSequenceNumber not copied into GetShardIteratorRequest

### ISSUE THREAD

**Issue by vkulikov** [akkadotnet/Alpakka#159]
https://github.com/akkadotnet/Alpakka/blob/26a9e78fd778fc7b9090a182db34bc685dee2c07/src/AWS/Kinesis/Akka.Streams.Kinesis/KinesisSourceStage.cs#L100-L108

`StartingSequenceNumber` must be copied when `ShardIteratorType` is set to `AFTER_SEQUENCE_NUMBER` or `AT_SEQUENCE_NUMBER`

**Comment by Aaronontheweb** [comment]
Closed via #160
