### ISSUE TITLE
Using AmqpConnectionDetails with SSL enabled always results with "localhost" endpoint 

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/Alpakka#164]
The following connection details:
```fsharp
let settings =
        AmqpConnectionDetails.Create("host22", 5671)
            .WithAutomaticRecoveryEnabled(true)
            .WithNetworkRecoveryInterval(TimeSpan.FromSeconds 1.0)
            .WithCredentials(AmqpCredentials.Create("foo", "1"))
            .WithSsl(SslOption("host22", enabled = true))
```
results with a `ConnectionFactory`, which's `Endpoint` is `localhost`. 

A workaround: use `AmqpConnectionUri.Create("amqps://foo:1@host22:5671")` instead.

**Comment by Aaronontheweb** [comment]
@vasily-kirichenko is this a bug with our code or the driver being used?

**Comment by vasily-kirichenko** [comment]
The driver?.. I'm not sure what you mean. I just expect the code ^^ to connect to "host22" via SSL, but it connects to "localhost".

**Comment by Aaronontheweb** [comment]
My bad, thought it might be an issue with the RabbitMQ driver - but no, it's probably an issue with how we propagate settings here: 

https://github.com/akkadotnet/Alpakka/blob/128574007475512834c7d65307a90d4f9ad8ab43/src/Amqp/Akka.Streams.Amqp.RabbitMq/AmqpConnector.cs#L13-L51

I'll ask @Arkatufus to look at it

**Comment by vasily-kirichenko** [comment]
Yeah, in the working branch: 
```
case AmqpConnectionUri connectionUri:
    factory.Uri = connectionUri.Uri;
```
the Uri setter (which is in RabbitMQ.Client library) does a lot of work (like constructing SslOptions if the schema is `amqps` and so on). I think it would be a good idea to check if that logic is copied here.

**Comment by Aaronontheweb** [comment]
`AmqpConnectionDetails` doesn't inherit from `AmqpConnectionUri` so that code _shouldn't_ be called, but it's something we can test easily enough.

**Comment by vasily-kirichenko** [comment]
Or, even better, just provide a details derivative which accepts a seq of raw amqp(s) Uris, and let RabbitMQ.Client lib parse them.

**Comment by vasily-kirichenko** [comment]
I mean, to provide a bunch of Uris in case of RMQ cluster.
