### ISSUE TITLE
Add nightly build support

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Alpakka#173]
So users can get access to nightlies.

**Comment by ismaelhamed** [comment]
@Aaronontheweb @Arkatufus I can see the nightly build is there, but I'm not sure if you guys are not publishing it or if you haven't made the feed publicly available (is a different one from Akka.NET's)

**Comment by Aaronontheweb** [comment]
Yeah looks like I still need to implement this - working on it now

**Comment by Aaronontheweb** [comment]
This is now working - uses the same nightly build feed as Akka.NET: https://getakka.net/community/getting-access-to-nightly-builds.html
