### ISSUE TITLE
Publish AMQP NuGet package

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/Alpakka#22]
Please, publish the AMQP package.

**Comment by vasily-kirichenko** [comment]
Found them https://www.nuget.org/profiles/AkkaNetContrib

**Comment by vasily-kirichenko** [comment]
Pleeeease :)

**Comment by Aaronontheweb** [comment]
@vasily-kirichenko you got it

**Comment by Aaronontheweb** [comment]
cc @alexvaluyskiy @marcpiechura do we have any CI on place on the `master` branch for this repository at the moment? Or is that a TBD?

**Comment by vasily-kirichenko** [comment]
@Aaronontheweb Do you mean you've published it? It's not listed on nuget.org

**Comment by Aaronontheweb** [comment]
https://www.nuget.org/packages/Akka.Streams.Amqp/ - ask and ye shall receive

**Comment by vasily-kirichenko** [comment]
Thank you! :)

**Comment by kryvicz** [comment]
@Aaronontheweb There is an obsolete version on NuGet and it doesn't work. Could you please publish an updated version. The actual version built from sources works well, so why not to publish it.
