### ISSUE TITLE
Relation between Akka.NET and Petabridge

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/Alpakka#3]
I want to make a statement here.
The Akka.NET project and organization is a separate entity from Aarons Petabridge.
I personally love what you @Aaronontheweb are doing and I am impressed with the success you have had.

But, when things like this `The Petabridge subscription does not cover support for these modules` sneak into the documentation and organizational repos, then the boundaries have become too much blurred.

Same rules must apply to everyone, if anyone else wants to run a business around Akka.NET, where do we draw the line whos business get exposed in the internal information?
(I have no intention on doing so, so it's not that, it's about principles, open, free, same rules for everyone)

I see no issues with linking to blogs or articles from the docs, but when someones personal support license pops up in here, then there is a problem with ownership and perception from the community.

**Comment by Silv3rcircl3** [comment]
Just for clarification, the same line exists in the jvm repo and therefore I kept it and replaced Lightbend with Petabridge, there was no request from Aaron to add it. 

Regarding you statement, I agree that this should be removed and handled separately. Wasn't clear to me while I created the repo, haven't even thought about it, so maybe that's a good opportunity to get it straight.

**Comment by rogeralsing** [comment]
No worries, and I didn't think there was any malice to it.
But I see a lot of confusion from users on where the boundaries are, so I just think it is important to be explicit about this, thats all :-)
