### ISSUE TITLE
Akka.Streams.SignalR

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/Alpakka#4]
I think, that good idea would be to add a source/sink support for SignalR. Ideally it should also cover a reactive streams API back to the client side - RxJs already implemented reactive-streams compliant API in form of [controlled observables](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/backpressure.md#controlled-observables).

**Comment by Aaronontheweb** [comment]
@Horusiath you should flesh out this README here with some instructions: https://github.com/akkadotnet/Alpakka/blob/dev/SignalR/README.md

**Comment by alexvaluyskiy** [comment]
Closed https://github.com/akkadotnet/Alpakka/pull/8
