### ISSUE TITLE
Kafka fails stage on producer getting disconnected

### ISSUE THREAD

**Issue by AndreSteenbergen** [akkadotnet/Alpakka#45]
When I use a long running producer without message for longer then 10 minutes the kafka idle time reaper comes along and disconnects the producer. Giving an error. I have never had issues producing after this message.

The ProducerStageLogic however exits with a FailedStage. To my knowledge I don't think this should occur like this. This error is in the logs `9092/bootstrap: Receive failed: Disconnected`.

I am in doubt if this piece of code is correct, but I don't know 100%
```
                Log.Error(error.Reason);

                if (!KafkaExtensions.IsBrokerErrorRetriable(error) && !KafkaExtensions.IsLocalErrorRetriable(error))
                {
                    var exception = new KafkaException(error);
                    FailStage(exception);
                }
```

**Comment by Arkatufus** [comment]
Akka.Streams.Kafka have been moved out of Alpakka into its own Github repo.
Closing this issue. Please re-open them in https://github.com/akkadotnet/Akka.Streams.Kafka if you're still having this problem.
