### ISSUE TITLE
Azure CloudQueue integration not compatible with Akka.Streams 1.3.10

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/Alpakka#46]
Running Akka.Streams 1.3.10 against the current CloudQueue integration causes an MissingMethod exception on the `SetHandler` method call in its `QueueSource.Logic` class.

Its probably some overload that changed or something.

**Comment by siudeks** [comment]
How to reproduce the issue?

**Comment by Danthar** [comment]
Simply use it. You will get an exception. But i think this issue was already fixed with this PR. 
https://github.com/akkadotnet/Alpakka/pull/51
Al it needs is a new release afaik. If that hasn't happened already.
