### ISSUE TITLE
Prepare Alpakka release

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/Alpakka#52]
A number of PR's have been merged lately and we want to put out a new release for Alpakka.

The follow projects need to be updated to the latest version of akka.streams (at the very least).

- Azure projects (Done)
- AMQP project
- Kafka. See https://github.com/AkkaNetContrib/Alpakka/pull/42
- AWS
- CSV
- SNS
- SignalR
- XML

Note that these are all simple update dependencies and increment version actions.
Ill be slowly working my way through these projects over the coming weeks as i get around to doing it. 

But if anyone would like to do some of the work. Make a comment here and claim a project (or 2, 3). Doing so would speed up the process.

**Comment by AndreSteenbergen** [comment]
I'll update AMQP v1.0 and Kafka.

**Comment by ptjhuang** [comment]
SignalR looks like it's still with the old SignalR version. Should there be a new project?

**Comment by Danthar** [comment]
No. Your right. Its not the latest Signalr. Current latest version is 2.4.0 i think.
Your welcome to update the signalr version as well.

Thats why i said in the starting post. _(at the very least)_ Updating project specific dependencies is also very welcome. But potentially comes with alot more work.
If its an easy update, or if you have the time (when its not). By all means, go right ahead. We will welcome the PR with 2 fingers on the merge button ;)

**Comment by Danthar** [comment]
Btw. I know a new minor release for akka.net is coming soonish. But don't let that stop anyone.

**Comment by bobanco** [comment]
AMQP is not up to date with the jvm one, we are few PRs behind, @vasily-kirichenko did some updates last time but i haven't checked if we are still there. If some one wants to take that task it would be good, otherwise i will do it over the weekend.

**Comment by ptjhuang** [comment]
> Its not the latest Signalr. Current latest version is 2.4.0 i think.
> Your welcome to update the signalr version as well.

My question's slightly different.  Current version for .NET fx classic is 2.4.0.  AspNetCore however, is radically different to SignalR for classic .NET FX.  If I modify this version, it would mean we break support for users still using classic .NET FX, as in, they can either have Akka 1.3.11 AND move their entire project to .Net Core, or nothing at all.

So I'm thinking it's more responsible to create a new SignalR sub-project for AspNetCore perhaps.  i.e. leave the current one there - I might bump the version of Akka to 1.3.11.  Then create a separate folder call it SignalR.AspNetCore and do work the against .NETstandard and AspNetCore.SignalR.  There're significant changes to the API in SignalR .NET core.

Is that OK?

**Comment by Aaronontheweb** [comment]
This is done
