### ISSUE TITLE
Net Standard Support for Akka Streams Azure Storage Queue

### ISSUE THREAD

**Issue by siudeks** [akkadotnet/Alpakka#58]
As a developer working with NET Core / Akka / Azure Storage Queue
I would like to convert existing Azure Storage Queue project to netstandard2
so that it would be reusable with new net core projects same as currently is used with net461

I changed type of project from net461 to netstandard2 and solution is still compilable, tests are green.

**Comment by Arkatufus** [comment]
We're overhauling the whole Alpakka repo right now. Azure StorageQueue is already updated to the latest version 9.3.3 in the dev branch. We will perform a move from `WindowsAzure.Storage` package to `Azure.Storage.Queues` package after all the dust has settled.

**Comment by siudeks** [comment]
@Arkatufus so probably the PR can be closed, isn't it ?

**Comment by Arkatufus** [comment]
Yessir :)
