### ISSUE TITLE
AMQP only works in localhost?

### ISSUE THREAD

**Issue by sleipnir** [akkadotnet/Alpakka#61]
Hello, I am trying to connect a Broker that is not available for localhost. But this example shows how to use NamedQueueSourceSettings.Create (DefaultAmqpConnection.Instance, queueName) .WithDeclarations (queueDeclaration) where DefaultAmqpConnection.Instance implies a local host with no authentication.
Can someone help me?
I would also like to know about the status of this project. Is he active?

Thanks

**Comment by Arkatufus** [comment]
You create `AmqpConnectionDetails` by calling `AmqpConnectionDetails.Create(string host, int port)` and then chains it with fluent interface to fill in the rest of the information.

Here is an example of this being used: https://github.com/akkadotnet/Alpakka/blob/dev/src/Amqp/Akka.Streams.Amqp.Tests/AmqpConnectorsTest.cs#L29-L34

You can read the details in the source code here: https://github.com/akkadotnet/Alpakka/blob/dev/src/Amqp/Akka.Streams.Amqp/Model.cs#L246-L319
