### ISSUE TITLE
SQS example is incorrect

### ISSUE THREAD

**Issue by anthony-steele-cko** [akkadotnet/Alpakka#63]
The demo example [in the README here](https://github.com/akkadotnet/Alpakka/blob/dev/Aws/SQS/README.md) is not correct, does not compile, beccause

`_materializer` is not defined, it is probably meant to be `materializer`.

`.Run(materializer)` does not return something that can be `await` ed.

I can't tell as a newcomer how to fix this, which is a blocker to trying to use this code.

**Comment by Horusiath** [comment]
You're right, there's a typo in a word `_materializer` (should be `materializer`). Could you share, what type is returned by `Run` method in your case? `SqsAckSink.Grouped` should materialize to .NET Task.

**Comment by anthony-steele-cko** [comment]
`.Run(materializer)` returns type `NotUsed`.

It looks like `SqsAckSink.Grouped` does return a `Task` as you say, but the code is `.To(SqsAckSink.Grouped(` which is at that point typed as `IRunnableGraph<Akka.NotUsed>`. The `.Select` and `.Create` also have the `Akka.NotUsed`

**Comment by Horusiath** [comment]
There's an overload of `To` method called `ToMaterialized`, which let's you select which materialized value of two combined streams are you interested in:

```csharp
using Amazon;
using Amazon.Runtime;
using Amazon.SQS;
using Akka.Actor;
using Akka.Streams;

var credentials = new BasicAWSCredentials(AccessKey, SecretKey);

using (var client = new AmazonSQSClient(credentials, RegionEndpoint.USEast1))
using (var system = ActorSystem.Create("system"))
using (var materializer = system.Materializer())
{
    var settings = SqsSourceSettings.Default
        .WithVisibilityTimeout(TimeSpan.FromSeconds(60));

    await SqsSource.Create(client, QueueUrl, settings)
        .Select(msg =>
        {
            // handle message
            Console.WriteLine($"Received message from SQS: {msg.Body}");
            // after we handled the message we need to take if off from the queue
            return MessageAction.Delete(msg);
        })
        .ToMaterialized(SqsAckSink.Grouped(client, QueueUrl), Keep.Right) // keep the materialized value from sink
        .Run(materializer);
}
```

**Comment by anthony-steele-cko** [comment]
I don't know what  the "materialized value of two combined streams" means yet or why I would pick one over the other.  I was hoping to get the example working in order to find out that kind of thing.

**Comment by Horusiath** [comment]
Materialized values are more described in the [docs](https://getakka.net/articles/streams/basics.html#defining-and-running-streams) - it's one of the core concepts of akka streams. Basically once stream is materialized, it produces some sort of the output value - this value depends on the particular stages used by the stream itself, and it's developer responsibility to define which of these values should be ignored and which not.

Most stages don't materialize to any value (in akka this is noted as `NotUsed` type). However some of them do, eg:

- `Source.Queue` will materialize to a queue (something that works like TPL `ChannelWriter<T>`), that will let you send the data into the stream manually.
- `.Aggregate` materializes to `Task<T>` which will complete once the upstream is closes and will return a value being result of aggregation function over all elements of the stream. 

Many finalizers (like `ForEach`, `Reduce` etc.) often define some `Task` as materialized value to let you await on it until upstream is closed or fails. The same is the case for `SqsAckSink.Grouped`. 

By default `source.To(sink)` method takes a materialized value from source, which is not what we want in the example above - as we want to wait for the sink to complete confirming incoming messages first. For that reason we need to instruct stream to make use of the sink's materialized value using `left.ToMaterialized(right, Keep.Right)` method. `Keep.Right` means that the result, we're interested about is send by the argument send to `ToMaterialized` method. There are others operators like `Keep.Left` and `Keep.Both` that let you navigate over this decision process.

**Comment by anthony-steele-cko** [comment]
So... is there a working example?

**Comment by anthony-steele-cko** [comment]
FYI, this at least compiles for me, will try to run it later:

```csharp
            using (var system = ActorSystem.Create("system"))
            using (var materializer = system.Materializer())
            {
                var settings = SqsSourceSettings.Default
                    .WithVisibilityTimeout(TimeSpan.FromSeconds(60));

                await SqsSource.Create(sqsClient, queueUrl, settings)
                    .Select(msg =>
                    {
                        // handle message
                        Console.WriteLine($"Received message from SQS: {msg.Body}");
                        // after we handled the message we need to take if off from the queue
                        return MessageAction.Delete(msg);
                    })
                    .ToMaterialized(SqsAckSink.Grouped(sqsClient, queueUrl), Keep.Right)
                    // we delete messages in batches
                    .Run(materializer);
            }
        }
```

and, probably more realistic in my case:

```csharp

        public async Task StartStream(IAmazonSQS sqsClient, string queueUrl)
        {
            using (var system = ActorSystem.Create("system"))
            using (var materializer = system.Materializer())
            {
                var settings = SqsSourceSettings.Default
                    .WithVisibilityTimeout(TimeSpan.FromSeconds(60));

                await SqsSource.Create(sqsClient, queueUrl, settings)
                    .SelectAsync(1, async msg => await Handler(msg))
                    .ToMaterialized(SqsAckSink.Grouped(sqsClient, queueUrl), Keep.Right)
                    // we delete messages in batches
                    .Run(materializer);
            }
        }
```

**Comment by anthony-steele-cko** [comment]
See https://github.com/akkadotnet/Alpakka/pull/64
