### ISSUE TITLE
Need to migrate SignalR.Core packages to Microsoft.AspNet.SignalR

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Alpakka#635]
https://www.nuget.org/packages/Microsoft.AspNet.SignalR - this is what we should be targeting inside, rather than:

https://github.com/akkadotnet/Alpakka/blob/145a17caa74d4e583591e52ecad97f4e6362279b/src/SignalR.AspNetCore/Akka.Streams.SignalR.AspNetCore/Akka.Streams.SignalR.AspNetCore.csproj#L13

**Comment by Arkatufus** [comment]
Microsoft.AspNet.SignalR is actually the old version that targets Net Framework, its getting deprecated.
https://docs.microsoft.com/en-us/previous-versions/aspnet/jj919047(v=vs.118)

**Comment by Arkatufus** [comment]
Closed by #639
